services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  fab-assistant:
    build: .
    container_name: fab-assistant
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama_data: